/**
 * scaffolders/agent.ts — Scaffolder para agentes AI (rbx-harness)
 *
 * Gera a estrutura completa de um agente RBX: manifests Kubernetes E o
 * manifest.yaml de governança per o schema rbx-harness v0.1.
 *
 * É o scaffolder mais rico do Eden porque agentes têm uma camada de contrato
 * além da infraestrutura: o manifest.yaml declara capabilities, limitations,
 * governance triggers e resource budgets antes mesmo de uma linha de código
 * do agente existir.
 *
 * Integração com rbx-harness (github.com/rbxrobotica/rbx-harness):
 *   - Schema: https://rbxsystems.com/schemas/rbx-harness/v0.1/manifest
 *   - O manifesto gerado começa com status: draft — o agente não recebe
 *     requisições até que um humano preencha os campos TODO e mude para active
 *   - Fields marcados TODO são propositais: capabilities, limitations e description
 *     são específicos do agente e não podem ser inferidos pelo Eden
 *
 * Arquivos gerados em rbx-infra/apps/prod/<name>/:
 *   manifest.yaml              — Contrato do agente (rbx-harness spec)
 *   schemas/
 *     request.schema.json      — Schema do payload de entrada (template)
 *     response.schema.json     — Schema do payload de saída (template)
 *   namespace.yml              — Namespace K8s
 *   middleware-https.yml       — Redirect HTTP→HTTPS
 *   deploy.yml                 — Deployment (porta 8080, /healthz probe, envFrom secret)
 *   svc.yml                    — Service ClusterIP
 *   ingress.yml                — Ingress com TLS (gerado apenas se --domain for fornecido)
 *   kustomization.yml          — Lista recursos (ingress.yml incluído condicionalmente)
 *
 * Diferença chave em relação aos outros scaffolders:
 *   Ingress é OPCIONAL. A maioria dos agentes RBX são internos — comunicam-se
 *   via Thalamus e não precisam de exposição HTTP pública. O Eden pergunta
 *   explicitamente antes de gerar o ingress.
 */

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

export interface AgentScaffoldOptions {
  product: string;
  role: string;
  domain?: string;
  image: string;
}

function agentManifest(name: string, opts: AgentScaffoldOptions): string {
  const today = new Date().toISOString().split("T")[0];
  return `# rbx-harness agent manifest
# Schema: https://rbxsystems.com/schemas/rbx-harness/v0.1/manifest
# Docs: https://github.com/rbxrobotica/rbx-harness

id: ${name}-v1
name: ${name}
version: 0.1.0
status: draft
product: ${opts.product}
description: >
  TODO: Describe what this agent does (min 50 chars). Include what it does
  AND what it does not do. Be explicit about scope and boundaries.

role: ${opts.role}

tags:
  - ${opts.product}

capabilities:
  inputs:
    - type: TODO_input_type
      description: TODO describe the input (min 10 chars)
      required_fields: []

  processing:
    modes:
      - on-demand
    analysis_types:
      - TODO

  outputs:
    - type: TODO_output_type
      format: structured-json

limitations:
  cannot_do:
    - "TODO: List hard boundaries — what this agent is absolutely prohibited from doing"

  should_defer:
    - "TODO: List conditions under which this agent must defer to a human or another agent"

  known_limitations:
    - "TODO: Honest assessment of this agent's weaknesses and failure modes"

interface:
  protocol_version: "1.0"
  request_schema: schemas/request.schema.json
  response_schema: schemas/response.schema.json
  timeout_seconds: 30
  max_retries: 3
  authentication: thalamus-managed

governance:
  audit_level: full
  output_retention: 30d
  human_review_required: []
  approval_required_for:
    - capability_expansion
    - governance_relaxation

resources:
  compute:
    cpu_cores: 0.5
    memory_gb: 1
    gpu_required: false
  tokens:
    max_per_request: 4096
    estimated_monthly: 0
    context_window: 8192
  storage:
    logs_gb_per_month: 1
    state_gb: 0

operational:
  owner: platform@rbxsystems.com
  documentation: README.md
  source: src/
  tests: tests/
  monitoring:
    success_rate_threshold: 0.99
    latency_p95_ms: 500
    alert_on_degradation: true
  deployment:
    environment: development
    rollout_strategy: direct
    rollback_trigger: "success_rate drops below 0.95 over 5 minutes"

changelog:
  - version: 0.1.0
    date: ${today}
    changes: Initial manifest generated by Eden IDP
    approved_by: eden-cli
`;
}

function requestSchema(name: string): string {
  return `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://rbxsystems.com/schemas/${name}/v1/request",
  "title": "${name} Request",
  "type": "object",
  "required": ["request_type", "data"],
  "properties": {
    "request_type": {
      "type": "string",
      "description": "TODO: enumerate valid request types"
    },
    "data": {
      "type": "object",
      "description": "TODO: define request payload structure"
    }
  }
}
`;
}

function responseSchema(name: string): string {
  return `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://rbxsystems.com/schemas/${name}/v1/response",
  "title": "${name} Response",
  "type": "object",
  "required": ["status"],
  "properties": {
    "status": {
      "type": "string",
      "enum": ["success", "error", "deferred"]
    },
    "data": {
      "type": "object",
      "description": "TODO: define response payload structure"
    },
    "error": {
      "type": "object",
      "properties": {
        "code": { "type": "string" },
        "message": { "type": "string" }
      }
    }
  }
}
`;
}

function ns(name: string): string {
  return `apiVersion: v1
kind: Namespace
metadata:
  name: ${name}
  labels:
    app.kubernetes.io/part-of: ${name}
    environment: production
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
`;
}

function agentDeploy(name: string, image: string): string {
  return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: ${name}
  labels:
    app.kubernetes.io/name: ${name}
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: ${name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${name}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${name}
        app.kubernetes.io/component: agent
    spec:
      containers:
        - name: ${name}
          image: ${image}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - secretRef:
                name: ${name}-secrets
                optional: true
`;
}

function agentSvc(name: string): string {
  return `apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: ${name}
  labels:
    app.kubernetes.io/name: ${name}
    app.kubernetes.io/part-of: ${name}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ${name}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
`;
}

function agentIngress(name: string, domain: string): string {
  return `apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${name}-ingress
  namespace: ${name}
  labels:
    app.kubernetes.io/name: ${name}-ingress
    app.kubernetes.io/part-of: ${name}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: ${name}-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ${domain}
      secretName: ${name}-tls
  rules:
    - host: ${domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${name}
                port:
                  number: 8080
`;
}

function middleware(name: string): string {
  return `apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: ${name}
spec:
  redirectScheme:
    scheme: https
    permanent: true
`;
}

function kustomization(name: string, withIngress: boolean): string {
  const resources = [
    "namespace.yml",
    "middleware-https.yml",
    "deploy.yml",
    "svc.yml",
    ...(withIngress ? ["ingress.yml"] : []),
  ].map((f) => `  - ${f}`).join("\n");

  return `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
${resources}

commonLabels:
  app.kubernetes.io/part-of: ${name}
  environment: production
`;
}

export function scaffoldAgent(
  infraPath: string,
  name: string,
  opts: AgentScaffoldOptions
): void {
  const outDir = join(infraPath, `apps/prod/${name}`);
  const schemasDir = join(outDir, "schemas");
  mkdirSync(outDir, { recursive: true });
  mkdirSync(schemasDir, { recursive: true });

  // rbx-harness manifest
  writeFileSync(join(outDir, "manifest.yaml"), agentManifest(name, opts));

  // request/response schemas
  writeFileSync(join(schemasDir, "request.schema.json"), requestSchema(name));
  writeFileSync(join(schemasDir, "response.schema.json"), responseSchema(name));

  // Kubernetes manifests
  writeFileSync(join(outDir, "namespace.yml"), ns(name));
  writeFileSync(join(outDir, "middleware-https.yml"), middleware(name));
  writeFileSync(join(outDir, "deploy.yml"), agentDeploy(name, opts.image));
  writeFileSync(join(outDir, "svc.yml"), agentSvc(name));

  const withIngress = !!opts.domain;
  if (withIngress) {
    writeFileSync(join(outDir, "ingress.yml"), agentIngress(name, opts.domain!));
  }

  writeFileSync(join(outDir, "kustomization.yml"), kustomization(name, withIngress));

  // core namespace
  writeFileSync(join(infraPath, `core/namespaces/${name}.yml`), ns(name));
}
